### PR TITLE
Update default maven version and checksum.

### PR DESCRIPTION
**Pull request by alexanderdavidpan**
### Description

This fixes an error where the url returns a 404 for the maven tar file.

### Issues Resolved

https://github.com/chef-cookbooks/maven/issues/92

### Check List

[✅] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
[ ] New functionality includes testing.
[✅] New functionality has been documented in the README if applicable (not applicable)
[✅] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by iennae** [comment]
@alexanderdavidpan Thanks for the PR. Could you amend your commit and sign it with -s to comply with DCO? Thank you!

**Comment by alexanderdavidpan** [comment]
@iennae I signed off on my commit. Thanks.

**Comment by tas50** [comment]
This is going to be problematic in the long run. As apache moves the project off the main site this will be a 404. We need to pull from archive since those don't cycle off

**Comment by alexanderdavidpan** [comment]
@tas50, Good point. I reverted the maven url to point to Apache archives.

**Comment by iennae** [comment]
Good catch @tas50. Thanks for updating @alexanderdavidpan

**Pull request merged**
