### PR TITLE
Changes to add settings LWRP to update maven settings and update to latest maven version

### PR DESCRIPTION
**Pull request by praste**
1. Added settings LWRP
2. Updated documentation
3. Changed default maven version to latest stable maven release 3.2.3

This fixes issues #43, #42, #48

### CODE REVIEW

**Comment by fletchowns** [comment]
Would be great to have a way to manipulate settings.xml

**Comment by praste** [comment]
Well author of this cookbook does not seem to agree.
You can write a wrapper cookbook, feel free to look at my fork of this cookbook

**Comment by tas50** [comment]
Since the CLA hasn't been signed in over 6 month for this PR I'm going to close it out at this point.  If the author would like to sign the CLA feel free to open up the PR again.

**Comment by praste** [comment]
May be its just me but a comment 'Signed CLA'  about a year ago

**Comment by tas50** [comment]
Oops missed that one.  Sorry

**Comment by praste** [comment]
I thought you would merge it :-|

**Pull request merged**
