### PR TITLE
force the snapshot update

### PR DESCRIPTION
**Pull request by namtzigla**
changed the `mvn` command line so in case the version of the artifact ends in `-SNAPSHOT` it will be updated on the next run.

### CODE REVIEW

**Comment by dluchinienoc** [comment]
+1 for this change.

A time-consuming workaround is to blow away the local Maven repository on each Chef converge (this assumes maven is running as root):
```
directory "#{ENV['HOME']}/.m2/repository" do
  action :delete
  recursive true
end
```

I say time-consuming because both the recursive delete and subsequently having to re-download artifacts add significant overhead to our Chef converges.

**Comment by giorgian** [comment]
Any news on this?

**Comment by namtzigla** [comment]
@giorgian we are using this patch for the last 2 years now w/o a problem. 
I guess that's the latest news on my part :)

**Comment by tas50** [comment]
@namtzigla If you want to rebase this I can merge it in

**Comment by namtzigla** [comment]
new PR #79

**Pull request closed without merging**
